---
name: cable_vasool
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  shared_preferences: null
  fluttertoast: ^7.1.1
  package_info: ^0.4.3
  graphql_flutter: ^3.1.0
  after_layout: ^1.0.7+2
  lazy_load_scrollview: ^1.2.0
  tuple: ^1.0.3
  flutter_phoenix: ^0.1.0
  logger: ^0.9.4
  file_picker: ^2.0.7
  csv: ^4.0.3
  responsive_framework: ^0.0.11
  intl: ^0.16.1
  random_color: ^1.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
